### ISSUE TITLE
Methods/Results Section Feedback

### ISSUE THREAD

**Issue by ghost** [b-nroths/MACS30200proj#3]
The description of each dataset is helpful. However, think about moving this information to an appendix. Try to use your data/methods section has prime real-estate for your study’s findings. The tables are helpful. However, they need a labels and proportions. The count alone does not provide readily intuitive information for the reader. Also, think about combining all of these tables into a single table for easy reference. Good graphs. Things to think about: (1) articles are usually printed in black and white, so the color distinctions will not be useful; (2) the graphs alone are not easily interpretable. be sure to include a discussion of your own analysis for each graph you provide; (3) re-label the graphs without the code notation. Finally, try to prevent the use of bulleted text as much as possible. Weave all necessary information into paragraph form.

**Comment by bnroths** [comment]
thanks for the feedback!
